### ISSUE TITLE
pom.xml file needs to be updated to reflect dependency to cloudsim 4.0 (currently says 3.0.3)

### ISSUE THREAD

**Issue by rozmov** [Cloudslab/cloudsimsdn#10]
Readme currently states that cloudsim 4 is needed, but the pom.xml file still requires 3.0.3.

Readme:
Program dependencies

> You have to download CloudSim (cloudsim-4.0), enter the project's root directory and execute mvn clean install to install the jar packages into your local maven repository.
> 
> Other dependencies are already included.

 pom file:
```
<dependency>
            <groupId>org.cloudbus.cloudsim</groupId>
            <artifactId>cloudsim</artifactId>
            <version>3.0.3</version>
</dependency>
```

**Comment by hetianzhang** [comment]
Fixed. Thanks.
