### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by Ichliebedich0505** [Cloudslab/cloudsimsdn#13]
I ran one of the examples: SimpleExample and the error showed that a required function named getCloudletFailedList() is missing in CloudletScheduler. Don't know if that's because I have made some mistake somewhere or just because the function is actually missing. Any helpful answer will be appreciated!

**Comment by hetianzhang** [comment]
Hi @Ichliebedich0505,

I didn't experience any error regarding that by directly running the SimpleExample. And it's better to specify the problem like your configuration of the example, where exactly the error happens, etc. Furthermore, you may want to check the new version has lots of bugs fixed.

Best regards
