### ISSUE TITLE
CloudsimSDN workload

### ISSUE THREAD

**Issue by akssus12** [Cloudslab/cloudsimsdn#16]
First, thanks to great to provide me a useful simulator for evaluation of edge computing and NFV,SDN. I want to ask some questions about simulator.
(1) I experimented SFC placement algorithm in two ways(One is using full workloads(4000 workloads), the other is using only 1 workloads. I found when i execute only 1 workloads, servetime of that workload is really time-consuming(about 25 seconds per) but when i execute 4000 workloads, servetime of that workloads is very short(0.1~1.1). Can i know the reason?
(2) Is it possible to change the processing/transmission delay depending on host/link utilization?

Best regards,

**Comment by ICarvalho** [comment]
Hi. 
Could you please tell me how do you get these workloads to run SFC experiments? I found those in the cloudsimsdn source file too small and I didn't find other similar workloads to test. 

Best regards, 

Igor.

**Comment by hetianzhang** [comment]
> Hi.
> Could you please tell me how do you get these workloads to run SFC experiments? I found those in the cloudsimsdn source file too small and I didn't find other similar workloads to test.
> 
> Best regards,
> 
> Igor.

Hi Igor,

Please check it out here:
https://github.com/Cloudslab/sfcwikiworkload

Best regards

**Comment by shaker402** [comment]
Re: : Hi  all Deer   cloudsimsdn  .for "workloads to run SFC experiments? " So     After you generate the workload files      how did you pass all these files  as args to eclipse for SFC experiments  so. I can't pass more than one file type CSV. For this program pleas help me how I pass these files as argument to eclipse thanks .

**Comment by hetianzhang** [comment]
> Re: : Hi all Deer cloudsimsdn .for "workloads to run SFC experiments? " So After you generate the workload files how did you pass all these files as args to eclipse for SFC experiments so. I can't pass more than one file type CSV. For this program pleas help me how I pass these files as argument to eclipse thanks .

Usage: [Policy] [SFCScale] [network topology file] [virtual topology file] [workload folder] [workload1] [workload2] [...]
```
LFF 0 your.physical.json your.virtual.json your-workload-folder/ 0_0_workload_wiki.csv 0_1_workload_wiki.csv ...
```
Please mind if your input workload is more than one, there is a space between the folder and the list of workload files. You can always modify the input of the example file anyway.

**Comment by hetianzhang** [comment]
Hi,

Sorry for the late replay, as I assume the original author will answer your question.

> First, thanks to great to provide me a useful simulator for evaluation of edge computing and NFV,SDN. I want to ask some questions about simulator.
> (1) I experimented SFC placement algorithm in two ways(One is using full workloads(4000 workloads), the other is using only 1 workloads. I found when i execute only 1 workloads, servetime of that workload is really time-consuming(about 25 seconds per) but when i execute 4000 workloads, servetime of that workloads is very short(0.1~1.1). Can i know the reason?

Could you share your test workload with me? Then I can check what is wrong.

> (2) Is it possible to change the processing/transmission delay depending on host/link utilization?

Yes, the simulator has already been designed to do so. However, different scheduling algorithms (resource sharing algorithms) of CPU processing and network transmission may have different results. You can look at the scheduling algorithms we provided as the template.  For example, for network transmission, you may have virtual links with different channel id (-1 and positive id). The networking operation system will first fulfill the bandwidth requirement of the positive-id channel. Then, non-positive id channels will share the remaining bandwidth. In a case when the sum of reserved bandwidth of positive-id channel exceeds the physical bandwidth, the networking operation system will assign the bandwidth based on the ratio.

Hope this answer will help.
> 
> Best regards,

**Comment by shaker402** [comment]
Thank you very much dear for this wonderful proposal. Yes, I faced this problem and made the appropriate amendment as I mentioned.  Finally the code worked correctly
