### ISSUE TITLE
Cannot creta project from Cloudsimsdn pom file

### ISSUE THREAD

**Issue by ICarvalho** [Cloudslab/cloudsimsdn#20]
Hi, 

I'm having some problems while installing cloudsimsdn using mvn clean install. follow is the returnd error:

Failed to execute goal on project cloudsimsdn: Could not resolve dependencies for project org.cloudbus:cloudsimsdn:jar:1.0: Failure to find org.cloudbus.cloudsim:cloudsim:jar:4.0 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -

Besides that, when I import the cloudsimsdn pom file in IntelliJ to create a project, it cannot recognize some imports like:

mport org.cloudbus.cloudsim.DatacenterCharacteristics;
import org.cloudbus.cloudsim.Host;
import org.cloudbus.cloudsim.Log;
import org.cloudbus.cloudsim.Storage;
import org.cloudbus.cloudsim.VmAllocationPolicy;
import org.cloudbus.cloudsim.core.CloudSim;

Therefore, I cannot test some scenarios because of such errors. 

Can anyone help me to solve them?

thanks

**Comment by xiaolalala1** [comment]
copy all of cloudsim-4.0-src-org.cloudbus.cloudsim code to the path of cloudsimsdn src-org.cloudbus.cloudsim ,then install mav again

**Comment by Marzieh-1373** [comment]
Hi.
when I try to run java -cp cloudsimsdn-1.0-with-dependencies.jar org.cloudbus.cloudsim.sdn.example.SDNExample MFF ../dataset-energy/energy-physical.json ../dataset-energy/energy-virtual.json ../dataset-energy/energy-workload.csv > results.out in cmd to run SimpleExample I face an Error :could not open or load org.cloudbus.cloudsim.sdn.example.SDNExampl and i ca not resolve this problem.

**Comment by xiaolalala1** [comment]
Hi,there is no SDNExample.It is SimpleExample.You try command java -cp cloudsimsdn-1.0-with-dependencies.jar org.cloudbus.cloudsim.sdn.example.SimpleExample MFF ../dataset-energy/energy-physical.json ../dataset-energy/energy-virtual.json ../dataset-energy/energy-workload.csv > results.out .
Or you use IDEA's run to direct run the file target/src/main/java/org/cloudbus/cloudsim/sdn/example/SimpleExample without run argumention.



At 2020-04-27 20:22:10, "Marzieh-1373" <notifications@github.com> wrote:

Hi.
when I try to run java -cp cloudsimsdn-1.0-with-dependencies.jar org.cloudbus.cloudsim.sdn.example.SDNExample MFF ../dataset-energy/energy-physical.json ../dataset-energy/energy-virtual.json ../dataset-energy/energy-workload.csv > results.out in cmd to run SimpleExample I face an Error :could not open or load org.cloudbus.cloudsim.sdn.example.SDNExampl and i ca not resolve this problem.

**Comment by Marzieh-1373** [comment]
i enter in cmd  java -cp cloudsimsdn-1.0-with-dependencies.jar org.cloudbus.cloudsim.sdn.example.SimpleExample MFF ../dataset-energy/energy-physical.json ../dataset-energy/energy-virtual.json ../dataset-energy/energy-workload.csv > results.out but unfortunately this previous error occur.
where I enter target/src/main/java/org/cloudbus/cloudsim/sdn/example/SimpleExample??
where id IDE run?

**Comment by xiaolalala1** [comment]
use IDEA to open the project.Download the cloudsimsdn.zip from GitHub




| |
angel
|
|
邮箱：xieyvxiao@163.com
|

Signature is customized by Netease Mail Master

On 04/28/2020 14:10, Marzieh-1373 wrote:

i enter in cmd java -cp cloudsimsdn-1.0-with-dependencies.jar org.cloudbus.cloudsim.sdn.example.SimpleExample MFF ../dataset-energy/energy-physical.json ../dataset-energy/energy-virtual.json ../dataset-energy/energy-workload.csv > results.out but unfortunately this previous error occur.
where I enter target/src/main/java/org/cloudbus/cloudsim/sdn/example/SimpleExample??
where id IDE run?

**Comment by Marzieh-1373** [comment]
what is IDEA?
I do not know about it.if you can,explain about it more

**Comment by xiaolalala1** [comment]
It is an application for java coding like eclipse.Full name is Intellij IDEA




| |
angel
|
|
邮箱：xieyvxiao@163.com
|

Signature is customized by Netease Mail Master

On 04/28/2020 15:25, Marzieh-1373 wrote:

what is IDEA?
I do not know about it.if you can,explain about it more

**Comment by Marzieh-1373** [comment]
How to run SimpleExample in IDEA?with terminal?please tell me step by step

**Comment by xiaolalala1** [comment]
First,open the project in IDEA.Second,find the SimpleExample in the directory of traget and double click the SimpleExample.Third,right click on the file name showed on the right of the window.Finally,choose Run



At 2020-04-28 16:08:32, "Marzieh-1373" <notifications@github.com> wrote:

How to run SimpleExample in IDEA?with terminal?please tell me step by step

**Comment by Marzieh-1373** [comment]
I can run with IDEA just SimpleExample.but unfortunately I can not run
SimpleExampleInterCloud.class.and one log occur in OUTPUT of IDEA.
that log is Usage: java SDNExample <LFF|MFF> [physical.json] [virtual.json]
[workload1.csv] [workload2.csv] [...]
Process finished with exit code 1.
can I run SimpeExampleInterCloud in IDEA?

**Comment by xiaolalala1** [comment]
sorry，ｉcan not tell you what to do because ｉmet the same error.i asked the author but no questions.




| |
angel
|
|
邮箱：xieyvxiao@163.com
|

Signature is customized by Netease Mail Master

On 04/30/2020 14:03, Marzieh-1373 wrote:

I can run with IDEA just SimpleExample.but unfortunately I can not run
SimpleExampleInterCloud.class.and one log occur in OUTPUT of IDEA.
that log is Usage: java SDNExample <LFF|MFF> [physical.json] [virtual.json]
[workload1.csv] [workload2.csv] [...]
Process finished with exit code 1.
can I run SimpeExampleInterCloud in IDEA?

**Comment by Marzieh-1373** [comment]
I want to run startExperimentSFC and I want to enter LFF 0 example-sfc/sfc-example-physical.json example-sfc/sfc-example-virtual-sfc-on.json example-sfc/ sfc-example-scale-workload.csv
but I face one error .this error is 
java.lang.NullPointerException: Error! cannot find a host for Workload:Processing:Len=4931,Start=0.009217527,Finish=0.0. VM=0 at org.cloudbus.cloudsim.sdn.physicalcomponents.SDNDatacenter.processNextActivityProcessing(SDNDatacenter.java:443)

**Comment by hetianzhang** [comment]
> I want to run startExperimentSFC and I want to enter LFF 0 example-sfc/sfc-example-physical.json example-sfc/sfc-example-virtual-sfc-on.json example-sfc/ sfc-example-scale-workload.csv
> but I face one error .this error is
> java.lang.NullPointerException: Error! cannot find a host for Workload:Processing:Len=4931,Start=0.009217527,Finish=0.0. VM=0 at org.cloudbus.cloudsim.sdn.physicalcomponents.SDNDatacenter.processNextActivityProcessing(SDNDatacenter.java:443)

Hi, the workload example-sfc/ sfc-example-scale-workload.csv is for the usage of virtual topology example-sfc/sfc-example-scale-virtual.json. 

If you look inside the code, https://github.com/Cloudslab/cloudsimsdn/blob/d0afad4a92ed8156bccb66d3fe73b48cfecad12f/src/main/java/org/cloudbus/cloudsim/sdn/physicalcomponents/SDNDatacenter.java#L434
the VMAllocationPolicy didn't assign any physical host to the VM in your case.

**Comment by Marzieh-1373** [comment]
Hi dear researchers,
Thanks for your response.I want to allocate Vm in Hosts with Genethic algorithm. but I do not know How I should implement it.
who knows about this?

**Comment by hetianzhang** [comment]
> Hi dear researchers,
> Thanks for your response.I want to allocate Vm in Hosts with Genethic algorithm. but I do not know How I should implement it.
> who knows about this?

Hi Marzie,

Please look into the running example we gave. Then, explore and extends those VM allocation policies (e.g. LFF, MFF, MFFGroup, etc) which implemented in the package "sdn.policies.vmallocation" (shown in the readme.md) based on your requirements. If you want separated allocation policies for VNFs from other VMs when parsing the JSON file of virtual topology, just apply a different policy accordingly.

Moreover, I would suggest you familiarize yourself with CloudSim first. The VM(VNF) allocation architecture is similar.

Regards

**Comment by CanVel00** [comment]
> copy all of cloudsim-4.0-src-org.cloudbus.cloudsim code to the path of cloudsimsdn src-org.cloudbus.cloudsim ,then install mav again

I am still having the issue
can you please help me out in this
