### ISSUE TITLE
GUI

### ISSUE THREAD

**Issue by xiaolalala1** [Cloudslab/cloudsimsdn#21]
Hi,
I have some questions regarding CloudsimSDN

1.What class or package is about GUI?I want to use GUI to build topology.
2.There is error when use run arguments you applied,the error is on PEs form org.cloudbus.cloudsim

**Comment by AbdoulayeDiop** [comment]
Hello,

Does someone know how to download and use the GUI for ClouSimSDN ?

**Comment by hetianzhang** [comment]
> Hi,
> I have some questions regarding CloudsimSDN
> 
> 1.What class or package is about GUI?I want to use GUI to build topology.
> 2.There is error when use run arguments you applied,the error is on PEs form org.cloudbus.cloudsim

Hi, I am not aware of any GUI available for the current version of the CloudSimSDN. Personally, I only use the tool provided by the sdn.example.topogenerators package.

**Comment by xiaolalala1** [comment]
我也没有找到gui的接口，但是运行作者的示例程序还是可以的，如果您知道了gui在哪里，麻烦您告诉我一下也，还有我再冒昧问一下，您用这个cloudsimSDN是干什么用，我当初是想运行作者publication里的论文里的实验，但是我对于仿真过程并不了解，非常感谢您能和我交流




| |
angel
|
|
邮箱：xieyvxiao@163.com
|

Signature is customized by Netease Mail Master

On 06/02/2020 22:25, TianZhang He wrote:

Closed #21.

**Comment by hetianzhang** [comment]
你好，由于我的论文需要，我在CloudSimSDN里加了一些nfv的模块和live migration的仿真模块。仿真过程你最好先了解一下cloudsim，然后再看cloudsimsdn。

**Comment by hetianzhang** [comment]
For the PEs bug within the CloudSim, could you download the newest version of CloudSim and run the experiment again to confirm the bug. I had put some patches months ago within the CloudSim.

**Comment by xiaolalala1** [comment]
嗯嗯嗯，非常感谢，我还没有做nfv的那个实验，你可以试着联系一下作者，如果我没有记错的话，那个nfv论文里有作者的邮箱




| |
angel
|
|
邮箱：xieyvxiao@163.com
|

Signature is customized by Netease Mail Master

On 06/02/2020 22:38, TianZhang He wrote:

你好，由于我的论文需要，我在CloudSimSDN里加了一些nfv的模块和live migration的仿真模块。仿真过程你最好先了解一下cloudsim，然后再看cloudsimsdn。
