### ISSUE TITLE
cloudsimSDN

### ISSUE THREAD

**Issue by Marzieh-1373** [Cloudslab/cloudsimsdn#22]
Hi.
I try to run SimpleExampleInterCloud of cloudsimSDN in Command Line but I face with a error.I enterJava -cp /*.. src.org.cloudbus.cloudsim.sdn.example.SimpleExampleInterCloud LFF  C:\Users\Life\Documents\NetBeansProjects\cloudsimSDN3\example-intercloud \intercloud.physical.json C:\Users\Life\Documents\NetBeansProjects\cloudsimSDN3\example-intercloud\intercloud.virtual.json   C:\Users\Life\Documents\NetBeansProjects\cloudsimSDN3\ example-intercloud\intercloud-example-workload.csv C:\Users\Life\Documents\NetBeansProjects\cloudsimSDN3\ example-intercloud\intercloud-example-workload2.csv    > resul.out in Command Line but it shows an Error:Could not find or load main class src.org.cloudbus.cloudsim.sdn.example.SimpleExampleInterCloud

**Comment by ree23456** [comment]
hi sir i am facing some problems mean what is the main file to run

**Comment by hetianzhang** [comment]
> Hi.
> I try to run SimpleExampleInterCloud of cloudsimSDN in Command Line but I face with a error.I enterJava -cp /*.. src.org.cloudbus.cloudsim.sdn.example.SimpleExampleInterCloud LFF C:\Users\Life\Documents\NetBeansProjects\cloudsimSDN3\example-intercloud \intercloud.physical.json C:\Users\Life\Documents\NetBeansProjects\cloudsimSDN3\example-intercloud\intercloud.virtual.json C:\Users\Life\Documents\NetBeansProjects\cloudsimSDN3\ example-intercloud\intercloud-example-workload.csv C:\Users\Life\Documents\NetBeansProjects\cloudsimSDN3\ example-intercloud\intercloud-example-workload2.csv > resul.out in Command Line but it shows an Error:Could not find or load main class src.org.cloudbus.cloudsim.sdn.example.SimpleExampleInterCloud

Please run configure the argument either within the run configurations of the IDE or export the executable jar and run it with "java -jar" plus the arguments.
