### ISSUE TITLE
VM replication

### ISSUE THREAD

**Issue by pledesma3** [Cloudslab/cloudsimsdn#6]
Would it be possible to perform VM replication on this simulator? If so, would a new class/package need to be created, or would I be able to modify any existing ones?

Thank you.

**Comment by Ahmadishapourabadi** [comment]
I have a error in class "VmAllocationPolicyPriorityFirst" how can i solve it

Error:(128, 99) java: incompatible types: java.util.Collection<org.cloudbus.cloudsim.sdn.Node> cannot be converted to java.util.Collection<? extends org.cloudbus.cloudsim.sdn.SDNHost>

**Comment by fatemehm** [comment]
Hi @pledesma3 
could you implement the VM replication on the CloudSimSDN? if yes, would you please tell me how I can do VM replication?

**Comment by hetianzhang** [comment]
Hi,

Please check out the VNF auto-scaling components and corresponding SFC rerouting. Extend them to suit your purposes.

Best regards
